### ISSUE TITLE
Exit Shell

### ISSUE THREAD

**Issue by figital** [webianproject/shell#161]
Couldn't figure out how to "exit shell" other than "ALT-TAB'ing" to the next application in Windows. 

If I had booted directly to this environment I'd want someway to "shutdown" or "return to command line prompts".

**Comment by benfrancis** [comment]
There will be a shut down button at the top right of the home screen, as in the mockup below.

![home_screen](https://cloud.githubusercontent.com/assets/552417/26152745/27f58034-3b00-11e7-8146-1a9e5f7190f6.png)
