### ISSUE TITLE
Links in GMail open as about:blank

### ISSUE THREAD

**Issue by benfrancis** [webianproject/shell#182]
STR:
* Click the Google Mail icon or load mail.google.com in a browser window
* Log into a GMail account
* View an email with hyperlinks in it
* Click on one of the hyperlinks

Expected:
* Link opens in a new browser window

Actual:
* New window opens but the URL is about:blank rather than the link included in the email

**Comment by benfrancis** [comment]
Also happens in Google Calendar, but Google News works as expected.

**Comment by benfrancis** [comment]
Debugging:

The detail.url of the `mozbrowseropenwindow` event payload is set to `about:blank` suggesting GMail does something weird that the Browser API isn't coping with.

@fabricedesre or @vingtetun Do you remember if we came across this in B2G?

**Comment by benfrancis** [comment]
Filed upstream bug https://github.com/mozilla/qbrt/issues/115

**Comment by fabricedesre** [comment]
No, I don't remember seeing that issue before.
